name: personal_lib
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  
  fonts:
    - family: Cheltenham
      fonts:
        - asset: assets/fonts/cheltenham/cheltenham-normal-400.ttf
        - asset: assets/fonts/cheltenham/cheltenham-normal-700.ttf
          weight: 700
    - family: Cheltenham Cond
      fonts:
        - asset: assets/fonts/cheltenham/cheltenham-cond-normal-500.ttf
        - asset: assets/fonts/cheltenham/cheltenham-cond-normal-700.ttf
          weight: 700
    - family: Cheltenham Wide
      fonts:
        - asset: assets/fonts/cheltenham/cheltenham-wide-normal-400.ttf
    - family: Franklin
      fonts:
        - asset: assets/fonts/franklin/franklin-normal-500.ttf
        - asset: assets/fonts/franklin/franklin-normal-700.ttf
          weight: 700
    - family: Franklin Cw
      fonts:
        - asset: assets/fonts/franklin/franklin-cword-normal-500.ttf
    - family: Imperial
      fonts:
        - asset: assets/fonts/imperial/imperial-normal-500.ttf
        - asset: assets/fonts/imperial/imperial-normal-700.ttf
          weight: 700

    
        
